### ISSUE TITLE
debug impossible

### ISSUE THREAD

**Issue by cognominal** [exceedsystem/vscode-macros#8]
I try to run debug a macro
It complains about a missing engine property. I guess it refers to some package.json file

<img width="491" alt="Capture d’écran 2022-01-31 à 03 49 11" src="https://user-images.githubusercontent.com/16176/151732651-f372e211-9f02-43c8-ac92-226b9f9e235f.png">

**Comment by exceedsystem** [comment]
@cognominal 

The error occurs because the Extension Development Host checks package.json for extension development.
VSCode Macros do not use package.json, so that error is not the direct cause of the macro not being able to run.

Also, the 'Debug a macro' command only starts the Extension Development Host.
If you would like to debug a macro, run the 'Run a macro' command on the Extension Development Host.

Regards.

**Comment by exceedsystem** [comment]
This issue has been closed.
If you have any problems, please issue again.
